Updated Vim document
nstankov-bg/docs.plutus-community.com pull request #32
Opened 2021-04-23 21:22 UTC by zarej

- Added line numbers in the configuration
- Removed nodejs installation part since it is already present in nix-shell
- Note in the beginning that nix-shell is using
- Better organized, fixed typos

2021-04-25 14:39 UTC, nstankov-bg approved these changes
Looks Great!
Will wait for @dino-  to approve as well.

2021-04-26 13:01 UTC, dino- commented on book/docs/setup/editors/vim.md
> +" Custom setings
Typo: "setings" should be "settings"

2021-04-26 13:03 UTC, dino- commented on book/docs/setup/editors/vim.md
> +\<leader\> key is ussually `\`
Typo: "ussually" should be "usually"

2021-04-26 13:04 UTC, dino- commented on book/docs/setup/editors/vim.md
> +Now you can enter to `vim` and execute `:PlugInstall` to install `coc.nvim`. After that you need to exit Vima and enter again to launch `coc-nvim` plugin. Next step is to configure it with vim comman
Typo: "Vima" should be "Vim"

2021-04-26 13:06 UTC, dino- requested changes
Looks great other than 3 typos I noticed and commented on. Lines 230, 239 and 262

2021-04-26 13:26 UTC, dino- approved these changes
Thank you!

2021-04-26 20:30 UTC, merged